import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/components/dashboard_ui/authProvider/authProvider";
import { SkeletonTheme } from "react-loading-skeleton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SkeletonTheme baseColor="#9c9c9c" highlightColor="#444">
          <AuthProvider>
            <ToastContainer />
            {children}
          </AuthProvider>
        </SkeletonTheme>
      </body>
    </html>
  );
}
